name = "GhilSellersEBM"
uuid = "384e9d69-9817-43fa-841b-44d84745ba4a"
authors = ["Maximilian Gelbrecht <maximilian.gelbrecht@posteo.de and contributors"]
version = "0.1.1"

[deps]
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
Interpolations = "0.13, 0.14"
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
